### ISSUE TITLE
responsive ?

### ISSUE THREAD

**Issue by MarieComet** [la-rache/la-rache.com#17]
Une version responsive serait-elle la bienvenue? Ou c'est trop éloigné de l'esprit de la rache ?
PR possible :).

**Comment by soullivaneuh** [comment]
@MarieComet Ca devrait etre faisable a condition que cela soit fait à la rache.

**Comment by aloisdg** [comment]
genre on scale le tout: https://css-tricks.com/scaled-proportional-blocks-with-css-and-javascript/

**Comment by marie-bnl** [comment]
Ptdrrrr l'abus

**Comment by fungiboletus** [comment]
Corrigé par #27
