### ISSUE TITLE
Version US?

### ISSUE THREAD

**Issue by agigleux** [la-rache/la-rache.com#26]
J'ai essayé d'expliquer la méthode à mes collègues américains qui n'ont pas compris. Ils ont traduit cela par "slapdash" ce qui n'est pas vraiment correcte car cela réduit la méthodologie de La RACHE a  un échec.

Est-ce qu'il existe une version US de la-rache.com qui me permettrait de partager cette bonne pratique avec nos amis américains ?

**Comment by Elysio** [comment]
A La RACHE:
https://translate.google.com/translate?sl=fr&tl=en&u=https%3A%2F%2Fwww.la-rache.com%2Findex.html 🙃

**Comment by agigleux** [comment]
Thanks for your answer, it's really in the spirit of the La-Rache methodology.
