### ISSUE TITLE
Système d'unités pifométriques

### ISSUE THREAD

**Issue by fredszaq** [la-rache/la-rache.com#4]
Bonjour, 

La version du document traitant de du système d'unités pifométriques présente sur le site est une version scannée peu pratique a utiliser quand on applique la méthode R.A.C.H.E. lors de la rédaction de documentation sur un projet et que l'on souhaite gagner du temps en utilisant la technique ancestrale du copié/collé/terminé (bah oui c'est compliqué de copier/coller depuis une image)

Il existe une version plus propre de ce document ici :  http://www.asqualab.com/documents/qualite/metrologie/19-unites_pifometriques.pdf je n'a par contre aucune idée des possibilités d'utiliser ce document directement sur le site (même si c'est peut être bonne application de la méthode R.A.C.H.E.  de pas trop s'en faire...)

Cordialement,

**Comment by feraudet** [comment]
Cool ! Je vais remplacer l'existant, je ne pense pas qu'on vienne me disputer le droit de l'utiliser, la moitié de Google l'utilise déjà !
